global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'apache'
    static_configs:
      - targets: ['apache-exporter:9117']

  - job_name: 'node-local'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'aws-servers'
    static_configs:
      - targets:
          - '184.73.163.15:9100'
          - '98.84.200.201:9100'
